routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
* For homepage - Login Page
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');


/*
* For login
*/
//Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
* For admin-end - Every admin view routes goes here
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
  Route::get('/', 'Admin\HomeController@index')->name('admin.dashboard');
  Route::post('/profile/changepass', 'Admin\ProfileController@edit')->name('profile.changepass');
  Route::resource('center', 'Admin\CenterController', ['except' => 'show']);

  Route::resource('course', 'Admin\CourseController', ['except' => 'show']);

  Route::resource('admin', 'Admin\AdminController', ['except' => 'show']);

  Route::resource('enrollment', 'Admin\EnrollmentController', ['except' => ['create', 'store']]);

  Route::resource('profile', 'Admin\ProfileController', ['except' => 'show']);
  // Tor routes goes here

});

/*
* For user-end - JSON results
*/
Route::group(['prefix' => 'api'], function(){
  Route::get('centers', 'Api\GetController@centers')->name('centers.get');
  Route::get('centers/{id}', 'Api\GetController@center')->name('centers.single');
  //Route::get('courses', 'Api\GetController@courses')->name('courses.get');
  Route::get('courses/{id}', 'Api\GetController@course');
  //Route::post('courses', 'Api\PostController@courses')->name('courses.post');
  //Route::get('admins', 'Api\GetController@admins')->name('admins.get');
  //Route::post('admins', 'Api\PostController@admins')->name('admins.post');
  //Route::get('profiles', 'Api\GetController@profiles')->name('profiles.get');
  //Route::post('profiles', 'Api\PostController@profiles')->name('profiles.post');
  //Route::get('enrollments', 'Api\GetController@enrollments')->name('enrollments.get');
  Route::post('enrollments/create', 'Api\PostController@enrollments')->name('enrollments.post');
});

Route::get('/test/frontend', function(){
  return view('testing.index');
});

Route::get('/test', function(){
  return view('test');
});
Route::get('/registration', 'UserController@index')->name('user.index');

Route::post('/user', 'UserController@getCourse')->name('user.courses');
Route::get('/test/show', 'Admin\CourseController@index');

resources/views/admin/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="{{ route('admin.dashboard') }}">
                        Home
                    </a>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy;
            <script>
                document.write(new Date().getFullYear())
            </script>
            <a href="http://www.kidstimebd.com">Kids Time BD</a>, made with love !
        </p>
    </div>
</footer>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<meta name="viewport" content="width=device-width" />

<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>@yield('title') | {{ config('app.name', 'Kids Time BD') }}</title>

resources/views/admin/layouts/messages.blade.php
@if (Session::has('success'))
  <div class="alert alert-success alert-dismissable fade in">
    <button type="button" aria-hidden="true" data-dismiss="alert" class="close btn btn-xs">×</button>
    <span><b><i class="material-icons">done</i>  Success - </b> {{ Session::get('success') }}</span>
  </div>
@endif

@if (Session::has('fail'))
  <div class="alert alert-danger alert-dismissable fade in">
    <button type="button" aria-hidden="true" data-dismiss="alert" class="close btn btn-xs">×</button>
    <span>
        <b><i class="material-icons">error</i>  Failed - </b> {{ Session::get('fail') }}</span>
  </div>
@endif

@if (count($errors) > 0)
  <div class="alert alert-danger alert-dismissable fade in">
    <button type="button" aria-hidden="true" data-dismiss="alert" class="close btn btn-xs">×</button>
    <span>
        <b><i class="material-icons">error</i>  Failed - </b> </span>
    <ul>
      @foreach ($errors->all() as $error)
        <li>
          {{ $error }}
        </li>
      @endforeach
    </ul>
  </div>
@endif

resources/views/admin/layouts/modal.blade.php
<div class="modal" id="confirm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Delete Confirmation</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <p>Are you sure, you want to delete ?</p>
                <p><i>Please note that, this deletion process can not be undone !</i></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Delete</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/admin/layouts/nav.blade.php
<nav class="navbar navbar-transparent navbar-absolute">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">@yield('title')</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">dashboard</i>
                        <p class="hidden-lg hidden-md">Dashboard</p>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="{{ route('admin.dashboard') }}"><i class="material-icons">home</i>&nbsp; Home</a>
                      </li>
                      <li>
                        <a href="http://kidstimebd.com" target="_blank"><i class="material-icons">near_me</i>&nbsp; Main Site</a>
                      </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="material-icons">person</i>
                        <p class="hidden-lg hidden-md">Profile</p>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <a href="{{route('profile.index')}}"><i class="material-icons">account_circle</i>&nbsp; Profile</a>
                      </li>
                      <li>
                          <a href="{{ route('logout') }}" onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();"><i class="material-icons">exit_to_app</i>&nbsp; Logout</a>

                                   <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                       {{ csrf_field() }}
                                   </form>
                      </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/admin/layouts/scripts.blade.php
<!--   Core JS Files   -->
<script src="{{ asset('assets/js/jquery-3.2.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/material.min.js') }}" type="text/javascript"></script>
<!--  Charts Plugin -->
<script src="{{ asset('assets/js/chartist.min.js') }}"></script>
<!--  Dynamic Elements plugin -->
<script src="{{ asset('assets/js/arrive.min.js') }}"></script>
<!--  PerfectScrollbar Library -->
<script src="{{ asset('assets/js/perfect-scrollbar.jquery.min.js') }}"></script>
<!--  Notifications Plugin    -->
<script src="{{ asset('assets/js/bootstrap-notify.js') }}"></script>
<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<!-- Material Dashboard javascript methods -->
<script src="{{ asset('assets/js/material-dashboard.js?v=1.2.0') }}"></script>
<!-- Material Dashboard DEMO methods, don't include it in your project! -->
<script src="{{ asset('assets/js/demo.js') }}"></script>

resources/views/admin/layouts/sidebar.blade.php
<div class="logo">
    <a href="{{ url('/') }}" class="simple-text">
        Kids Time BD
    </a>
</div>
<div class="sidebar-wrapper">
    <ul class="nav">
        <li class="{{ Request::url() === route('admin.dashboard') ? 'active' : '' }}">
            <a href="{{ route('admin.dashboard') }}">
                <i class="material-icons">dashboard</i>
                <p>Dashboard</p>
            </a>
        </li>
        <li class="{{ (Request::url() === route('center.index') || Request::url() === route('center.create')) ? 'active' : '' }}">
            <a href="{{ route('center.index') }}">
                <i class="material-icons">place</i>
                <p>Centers</p>
            </a>
        </li>
        <li class="{{ (Request::url() === route('course.index') || Request::url() === route('course.create')) ? 'active' : '' }}">
            <a href="{{route('course.index')}}">
                <i class="material-icons">list</i>
                <p>Courses</p>
            </a>
        </li>
        <li class="{{ (Request::url() === route('enrollment.index')) ? 'active' : '' }}">
            <a href="{{ route('enrollment.index') }}">
                <i class="material-icons">assignment</i>
                <p>Enrollments</p>
            </a>
        </li>
        <li class="{{ (Request::url() === route('admin.index') || Request::url() === route('admin.create')) ? 'active' : '' }}">
            <a href="{{route('admin.index')}}">
                <i class="material-icons">people</i>
                <p>Admins</p>
            </a>
        </li>
        <li class="active-pro">
            <a href="http://kidstimebd.com" target="_blank">
                <i class="material-icons">near_me</i>
                <p>Go to Main Site</p>
            </a>
        </li>
    </ul>
</div>

resources/views/admin/layouts/styles.blade.php
<link rel="apple-touch-icon" sizes="76x76" href="{{ asset('assets/img/apple-icon.png') }}" />
<link rel="icon" type="image/png" href="{{ asset('assets/img/favicon.png') }}" />
<!-- Bootstrap core CSS     -->
<link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" />
<!--  Material Dashboard CSS    -->
<link href="{{ asset('assets/css/material-dashboard.css?v=1.2.0') }}" rel="stylesheet" />
<!--  CSS for Demo Purpose, don't include it in your project     -->
<link href="{{ asset('assets/css/demo.css') }}" rel="stylesheet" />
<!--     Fonts and icons     -->
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>