routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
* For homepage - Login Page
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');


/*
* For login
*/
//Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
* For admin-end - Every admin view routes goes here
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
  Route::get('/', 'Admin\HomeController@index')->name('admin.dashboard');
  Route::post('/profile/changepass', 'Admin\ProfileController@edit')->name('profile.changepass');
  Route::resource('center', 'Admin\CenterController', ['except' => 'show']);

  Route::resource('course', 'Admin\CourseController', ['except' => 'show']);

  Route::resource('admin', 'Admin\AdminController', ['except' => 'show']);

  Route::resource('enrollment', 'Admin\EnrollmentController', ['except' => ['create', 'store']]);

  Route::resource('profile', 'Admin\ProfileController', ['except' => 'show']);
  // Tor routes goes here

});

/*
* For user-end - JSON results
*/
Route::group(['prefix' => 'api'], function(){
  Route::get('centers', 'Api\GetController@centers')->name('centers.get');
  Route::get('centers/{id}', 'Api\GetController@center')->name('centers.single');
  //Route::get('courses', 'Api\GetController@courses')->name('courses.get');
  Route::get('courses/{id}', 'Api\GetController@course');
  //Route::post('courses', 'Api\PostController@courses')->name('courses.post');
  //Route::get('admins', 'Api\GetController@admins')->name('admins.get');
  //Route::post('admins', 'Api\PostController@admins')->name('admins.post');
  //Route::get('profiles', 'Api\GetController@profiles')->name('profiles.get');
  //Route::post('profiles', 'Api\PostController@profiles')->name('profiles.post');
  //Route::get('enrollments', 'Api\GetController@enrollments')->name('enrollments.get');
  Route::post('enrollments/create', 'Api\PostController@enrollments')->name('enrollments.post');
});

Route::get('/test/frontend', function(){
  return view('testing.index');
});

Route::get('/test', function(){
  return view('test');
});
Route::get('/registration', 'UserController@index')->name('user.index');

Route::post('/user', 'UserController@getCourse')->name('user.courses');
Route::get('/test/show', 'Admin\CourseController@index');

app/Enrollment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Enrollment extends Model
{
  public function course(){
    return $this->belongsTo('App\Course');
  }
}

app/Http/Controllers/Admin/EnrollmentController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Enrollment;
use App\Course;
use Session;

class EnrollmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $enrolls = Enrollment::with('course')->get(['id', 'enrollment_id', 'course_id', 'child_name', 'mother_name', 'father_name', 'contact_no', 'status']);
        return view('admin.enrollment.index')->with('enrolls', $enrolls);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      //  $courses = Course::with('center')->get(['title', 'id', 'center_id']);

      //  return view('admin.enrollment.create')->with('courses', $courses);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $enrollment = Enrollment::with('course')->find($id);
        return view('admin.enrollment.show')->with('enrollment', $enrollment);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $enrollment = Enrollment::with('course')->find($id);
        $courses = Course::all(['id', 'title']);

        return view('admin.enrollment.edit')->with('enrollment', $enrollment)->with('courses', $courses);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $enrollment = Enrollment::find($request->id);

        $enrollment->course_id = $request->course_id;
        $enrollment->child_name = $request->child_name;
        $enrollment->mother_name = $request->mother_name;
        $enrollment->father_name = $request->father_name;
        $enrollment->age = $request->age;
        $enrollment->contact_no = $request->contact_no;
        $enrollment->address = $request->address;
        $enrollment->email = $request->email;
        $enrollment->transaction_no = $request->transaction_no;
        $enrollment->status = $request->status;

        $enrollment->save();

        Session::flash('success', 'The enrollment is successfully updated !');
        return redirect()->route('enrollment.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
      // For deleting multiple rows pass the array of ids
      $enrollment = Enrollment::destroy($request->id);

      Session::flash('success', 'The enrollment is successfully deleted !');
      return redirect()->route('enrollment.index');
    }
}

resources/views/admin/enrollment/create.blade.php
@extends('admin.main')

@section('title', 'Create Enrollment')

@section('page-styles')
  <!-- Form Validation Parsley  -->
  <link rel="stylesheet" type="text/css" href="{{ asset('css/validator/parsley.css') }}" />
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Create Enrollment</h4>
                        <p class="category">Create new Enrollment</p>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('enrollment.store') }}" data-parsley-validate="">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Child Name</label>
                                        <input type="text" class="form-control" name="child_name" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Father Name</label>
                                        <input type="text" class="form-control" name="father_name" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Mother Name</label>
                                        <input type="text" class="form-control" name="mother_name" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Select Course</label>
                                        <select class="form-control" name="course_id" required="">
                                          @foreach($courses as $course)
                                              <option value="{{ $course->id }}">Course : {{ $course->title }} | Center: {{ $course->center->name }}</option>
                                          @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Age</label>
                                      <input type="text" class="form-control" name="age" required="" data-parsley-type="number" max="12" min="4">
                                  </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Address</label>
                                        <input type="text" class="form-control" name="address" required="" maxlength="255">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Contact No</label>
                                        <input type="text" class="form-control" name="contact_no">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Email</label>
                                        <input type="text" class="form-control" name="email">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Transaction No</label>
                                        <input type="text" class="form-control" name="transaction_no">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Create</button>
                            <a href="{{ route('enrollment.index') }}" class="btn btn-primary pull-right">Back</a>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-scripts')
	<!-- Form Validation Parsley  -->
	<script src="{{ asset('js/validator/parsley.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/enrollment/edit.blade.php
@extends('admin.main')

@section('title', 'Edit Enrollment')

@section('page-styles')
  <!-- Form Validation Parsley  -->
  <link rel="stylesheet" type="text/css" href="{{ asset('css/validator/parsley.css') }}" />
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Edit Enrollment</h4>
                        <p class="category">Enrollment Code : ({{ $enrollment->enrollment_id }})</p>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('enrollment.update', [$enrollment->id]) }}" data-parsley-validate="">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put" />
                            <input type="hidden" name="id" value="{{ $enrollment->id }}" />
                              <div class="row">
                                  <div class="col-md-12">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Enrolled Course</label>
                                          <select class="form-control" name="course_id" required="">
                                            @foreach($courses as $course)
                                                <option value="{{$course->id}}" {{ ($course->id === $enrollment->course->id) ? ' selected="selected"' : '' }}>{{ $course->title }}</option>
                                            @endforeach
                                          </select>
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Child Name</label>
                                          <input type="text" class="form-control" name="child_name" value="{{ $enrollment->child_name }}" required="" maxlength="100">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Mother's Name</label>
                                          <input type="text" class="form-control" name="mother_name" value="{{ $enrollment->mother_name }}" required="" maxlength="100">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Father's Name</label>
                                          <input type="text" class="form-control" name="father_name" value="{{ $enrollment->father_name }}" required="" maxlength="100">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Age</label>
                                          <input type="text" class="form-control" name="age" value="{{ $enrollment->age }}" required="" data-parsley-type="number" max="12" min="4">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Contact No.</label>
                                          <input type="text" class="form-control" name="contact_no" value="{{ $enrollment->contact_no }}" required="" data-parsley-type="number">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Email</label>
                                          <input type="email" class="form-control" name="email" value="{{ $enrollment->email }}"  required="" maxlength="50">
                                      </div>
                                  </div>
                                  <div class="col-md-12">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Address</label>
                                          <input type="text" class="form-control" name="address" value="{{ $enrollment->address }}"  required="" maxlength="255">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Transaction No.</label>
                                          <input type="text" class="form-control" name="transaction_no" value="{{ $enrollment->transaction_no }}" data-parsley-type="alphanum">
                                      </div>
                                  </div>
                                  <div class="col-md-6">
                                      <div class="form-group label-floating">
                                          <label class="control-label">Status</label>
                                          <select name="status" class="form-control" required="" data-parsley-type="integer">
                                            <option value="1" {{ ($enrollment->status === 1) ? 'selected' : '' }}>Approved</option>
                                            <option value="0" {{ ($enrollment->status === 0) ? 'selected' : '' }}>Pending</option>
                                          </select>
                                      </div>
                                  </div>
                              </div>
                            <button type="submit" class="btn btn-primary pull-right">Confirm</button>
                            <a href="{{ route('enrollment.index') }}" class="btn btn-primary pull-right">Back</a>

                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-scripts')
	<!-- Form Validation Parsley  -->
	<script src="{{ asset('js/validator/parsley.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/enrollment/index.blade.php
@extends('admin.main')

@section('title', 'Enrollments')
@section('page-styles')
	<!-- DataTables -->
	<link href="{{ asset('css/datatable/dataTables.bootstrap.min.css') }}" rel="stylesheet" />
@endsection


@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<!--<a href="/admin/enrollment/create" type="button" class="btn btn-default">Create New Enrollment</a>-->
			<div class="card">
				<div class="card-header" data-background-color="orange">
					<h4 class="title">Enrollments</h4>
					<p class="category">All enrollment List</p>
				</div>
				<div class="card-content table-responsive">
					@if ($enrolls)

					<table id="datatable-all" class="table" data-form="deleteForm">
						<thead class="text-primary">
							<th>Enrollment Code</th>
							<th>Course <small>(Course Code)</small></th>
							<th>Child Name</th>
							<th>Mother Name</th>
							<th>Father Name</th>
							<th>Contact No</th>
							<th>Status</th>
							<th></th>
							<th></th>
							<th></th>
						</thead>
						<tbody>
							@foreach ($enrolls as $enroll)
							<tr>
							<td>{{$enroll->enrollment_id}}</td>
							<td>{{ $enroll->course->title }} <small>({{ $enroll->course->course_id }})</small></td>
							<td>{{$enroll->child_name}}</td>
							<td>{{$enroll->mother_name}}</td>
							<td>{{$enroll->father_name}}</td>
							<td>{{$enroll->contact_no}}</td>
							<td>{{ ($enroll->status) ? 'Approved' : 'Pending' }}</td>
							<td><a href="{{ route('enrollment.show', [$enroll->id]) }}" class="btn btn-success btn-sm">Details</a></td>
							<td><a href="{{ route('enrollment.edit', [$enroll->id]) }}" class="btn btn-info btn-sm">Edit</a></td>
							<td>
								<form class="form-delete" method="POST" action="{{ route('enrollment.destroy', [$enroll->id]) }}">
									{{ csrf_field() }}
									<input type="hidden" name="_method" value="delete" />
									<input type="hidden" name="id" value="{{ $enroll->id }}" />
									<input type="submit" class="btn btn-danger btn-xs" value="Delete"/>
								</form>
							</td>
						</tr>
							@endforeach
						</tbody>
					</table>
					@else
						<h5>No Item's yet, Please add a Center.</h5>
					@endif
				</div>
			</div>
		</div>
	</div>
</div>


<!-- Confirmation Modal Box -->
@include('admin.layouts.modal')

@endsection

@section('page-scripts')
	<!-- DataTables -->
	<script src="{{ asset('js/datatable/jquery.dataTables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/datatable/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

	<!-- page script -->
	<script>
	  $(function () {
	    $('#datatable-all').DataTable()
	  })
	</script>

	<script>
	// For Deletion Confirmation Modal
	$('table[data-form="deleteForm"]').on('click', '.form-delete', function(e){
	    e.preventDefault();
	    var $form=$(this);
	    $('#confirm').modal({ backdrop: 'static', keyboard: false })
	        .on('click', '#delete-btn', function(){
	            $form.submit();
	        });
	});
	</script>
@endsection

resources/views/admin/enrollment/show.blade.php
@extends('admin.main')

@section('title', 'Show Enrollment')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Show Enrollment</h4>
                        <p class="category">Enrollment Code : ({{ $enrollment->enrollment_id }})</p>
                    </div>
                    <div class="card-content">
                        <div class="row">
                            <div class="col-md-6">
                              <div class="col-md-12">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Child Name</label>
                                      <p class="lead">
                                        {{ $enrollment->child_name }}
                                      </p>
                                      <p>
                                        <label class="tim-note">Age :</label> {{ $enrollment->age }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-12">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Registered Course</label>
                                      <p class="lead">
                                        {{ $enrollment->course->title }} <small>({{ $enrollment->course->course_id }})</small>
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-12">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Status</label>
                                      <p class="lead">
                                        {{ ($enrollment->status) ? 'Approved' : 'Pending' }}
                                      </p>
                                  </div>
                              </div>
                            </div>
                            <div class="col-md-6">
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Father's Name</label>
                                      <p class="">
                                        {{ $enrollment->father_name }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Mother's Name</label>
                                      <p class="">
                                        {{ $enrollment->mother_name }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Contact No.</label>
                                      <p class="">
                                        {{ $enrollment->contact_no }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Email</label>
                                      <p class="">
                                        {{ $enrollment->email }}
                                      </p>
                                  </div>
                              </div>

                              <div class="col-md-12">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Address</label>
                                      <p class="">
                                        {{ $enrollment->address }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Transaction No.</label>
                                      <p class="">
                                        {{ $enrollment->transaction_no }}
                                      </p>
                                  </div>
                              </div>
                              <div class="col-md-5">
                                  <div class="form-group label-floating">
                                      <label class="control-label">Enrolled at</label>
                                      <p class="">
                                        {{ \Carbon\Carbon::parse($enrollment->created_at)->format('d/m/Y - H:i:s a') }}
                                      </p>
                                  </div>
                              </div>
                            </div>
                        </div>
                        <a href="{{ route('enrollment.index') }}" class="btn btn-primary pull-right">Back</a>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection