routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
* For homepage - Login Page
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');


/*
* For login
*/
//Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
* For admin-end - Every admin view routes goes here
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
  Route::get('/', 'Admin\HomeController@index')->name('admin.dashboard');
  Route::post('/profile/changepass', 'Admin\ProfileController@edit')->name('profile.changepass');
  Route::resource('center', 'Admin\CenterController', ['except' => 'show']);

  Route::resource('course', 'Admin\CourseController', ['except' => 'show']);

  Route::resource('admin', 'Admin\AdminController', ['except' => 'show']);

  Route::resource('enrollment', 'Admin\EnrollmentController', ['except' => ['create', 'store']]);

  Route::resource('profile', 'Admin\ProfileController', ['except' => 'show']);
  // Tor routes goes here

});

/*
* For user-end - JSON results
*/
Route::group(['prefix' => 'api'], function(){
  Route::get('centers', 'Api\GetController@centers')->name('centers.get');
  Route::get('centers/{id}', 'Api\GetController@center')->name('centers.single');
  //Route::get('courses', 'Api\GetController@courses')->name('courses.get');
  Route::get('courses/{id}', 'Api\GetController@course');
  //Route::post('courses', 'Api\PostController@courses')->name('courses.post');
  //Route::get('admins', 'Api\GetController@admins')->name('admins.get');
  //Route::post('admins', 'Api\PostController@admins')->name('admins.post');
  //Route::get('profiles', 'Api\GetController@profiles')->name('profiles.get');
  //Route::post('profiles', 'Api\PostController@profiles')->name('profiles.post');
  //Route::get('enrollments', 'Api\GetController@enrollments')->name('enrollments.get');
  Route::post('enrollments/create', 'Api\PostController@enrollments')->name('enrollments.post');
});

Route::get('/test/frontend', function(){
  return view('testing.index');
});

Route::get('/test', function(){
  return view('test');
});
Route::get('/registration', 'UserController@index')->name('user.index');

Route::post('/user', 'UserController@getCourse')->name('user.courses');
Route::get('/test/show', 'Admin\CourseController@index');

app/Center.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Center extends Model
{
  public function courses(){
    return $this->hasMany('App\Course');
  }
}

app/Http/Controllers/Admin/CenterController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Center;
use Session;

class CenterController extends Controller
{




    // On constructor we need to check Auth Middleware
    // --------------------------------------------------






    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $centers = Center::all();
        return view('admin.center.index')->with('centers', $centers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.center.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      // Validation

      // -----------------------
      $centers = Center::all();

      if($centers->isEmpty()){
        $last_center_code = 3001;

        $center = new Center;

        $center->center_id = $last_center_code;
        $center->name = $request->name;
        $center->location_heading = $request->location;
        $center->address = $request->address;
        $center->office_manager = $request->manager;
        $center->office_contact_no = $request->contact;
        $center->office_email = $request->email;

        $center->save();

        Session::flash('success', 'Center has been added successfully !');
        return redirect()->route('center.index');
      }

      $centers = null;

      $last_entry = Center::orderBy('center_id', 'desc')->first();
      $last_center_code = $last_entry->center_id + 1;

      $center = new Center;

      $center->center_id = $last_center_code;
      $center->name = $request->name;
      $center->location_heading = $request->location;
      $center->address = $request->address;
      $center->office_manager = $request->manager;
      $center->office_contact_no = $request->contact;
      $center->office_email = $request->email;

      $center->save();

      Session::flash('success', 'Center has been added successfully !');
      return redirect()->route('center.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      Session::flash('fail', 'The Requested page is not available !');
      return redirect()->route('center.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $center = Center::find($id);
        return view('admin.center.edit')->with('center', $center);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
      $center = Center::find($request->id);

      $center->name = $request->name;
      $center->location_heading = $request->location;
      $center->address = $request->address;
      $center->office_manager = $request->manager;
      $center->office_contact_no = $request->contact;
      $center->office_email = $request->email;
      $center->status = $request->status;

      $center->save();

      Session::flash('success', 'Center has been updated successfully !');
      return redirect()->route('center.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
      $center = Center::find($request->id);

      $center->delete();

      Session::flash('success', 'Center has been deleted successfully !');
      return redirect()->route('center.index');
    }
}

resources/views/admin/center/create.blade.php
@extends('admin.main')

@section('title', 'Create Center')

@section('page-styles')
  <!-- Form Validation Parsley  -->
  <link rel="stylesheet" type="text/css" href="{{ asset('css/validator/parsley.css') }}" />
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Create Center</h4>
                        <p class="category">Create new Center</p>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('center.store') }}" data-parsley-validate="">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Name</label>
                                        <input type="text" class="form-control" name="name" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Location</label>
                                        <input type="text" class="form-control" name="location" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Detail address</label>
                                        <input type="text" class="form-control" name="address" required="" maxlength="255">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Manager</label>
                                        <input type="text" class="form-control" name="manager" maxlength="50">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Contact No</label>
                                        <input type="text" class="form-control" name="contact" maxlength="15" data-parsley-type="digits">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Email</label>
                                        <input type="email" class="form-control" name="email" data-parsley-type="email" maxlength="50">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Create</button>
                            <a href="{{ route('center.index') }}" class="btn btn-primary pull-right">Back</a>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-scripts')
	<!-- Form Validation Parsley  -->
	<script src="{{ asset('js/validator/parsley.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/center/edit.blade.php
@extends('admin.main')

@section('title', 'Edit Center')

@section('page-styles')
  <!-- Form Validation Parsley  -->
  <link rel="stylesheet" type="text/css" href="{{ asset('css/validator/parsley.css') }}" />
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Edit Center</h4>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('center.update', [$center->id]) }}" data-parsley-validate="">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put" />
                            <input type="hidden" name="id" value="{{ $center->id }}" />
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Name</label>
                                        <input type="text" class="form-control" name="name" value="{{ $center->name }}" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Location</label>
                                        <input type="text" class="form-control" name="location" value="{{ $center->location_heading }}" required="" maxlength="100">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Detail address</label>
                                        <input type="text" class="form-control" name="address" value="{{ $center->address }}" required="" maxlength="255">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Manager</label>
                                        <input type="text" class="form-control" name="manager" value="{{ $center->office_manager }}" maxlength="50">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Contact No</label>
                                        <input type="text" class="form-control" name="contact" value="{{ $center->office_contact_no }}" maxlength="15" data-parsley-type="digits">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Office Email</label>
                                        <input type="email" class="form-control" name="email" value="{{ $center->office_email }}" data-parsley-type="email" maxlength="50">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Status</label>
                                        <select name="status" class="form-control" required="" data-parsley-type="integer">
                                          <option value="1" {{ ($center->status === 1) ? 'selected' : '' }}>Enable</option>
                                          <option value="0" {{ ($center->status === 0) ? 'selected' : '' }}>Disable</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Confirm</button>
                            <a href="{{ route('center.index') }}" class="btn btn-primary pull-right">Back</a>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('page-scripts')
	<!-- Form Validation Parsley  -->
	<script src="{{ asset('js/validator/parsley.min.js') }}" type="text/javascript"></script>
@endsection

resources/views/admin/center/index.blade.php
@extends('admin.main')

@section('title', 'Centers')

@section('page-styles')
	<!-- DataTables -->
	<link href="{{ asset('css/datatable/dataTables.bootstrap.min.css') }}" rel="stylesheet" />
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<a href="{{ route('center.create') }}" type="button" class="btn btn-default">Create New Center</a>
			<div class="card">
				<div class="card-header" data-background-color="orange">
					<h4 class="title">Centers</h4>
					<p class="category">All center List</p>

				</div>
				<!--
				<div class="col-md-12">
					<div class="dropdown" style="padding: 20px;">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="material-icons">border_color</i>&nbsp; Actions
						</a>
						<ul class="dropdown-menu">
								<li>
										<a href="#" id="btnDeleteSelected"><i class="material-icons">close</i>&nbsp; Delete Selected</a>
								</li>
								<li>
										<a href=""><i class="material-icons">close</i>&nbsp; Delete All</a>
								</li>
						</ul>
					</div>
				</div>
				-->
				<div class="card-content table-responsive">
					@if ($centers)

					<table id="datatable-all" class="table table-striped" data-form="deleteForm">
						<thead class="text-primary">
							<!--<th></th>-->
							<th>Center Code</th>
							<th>Name</th>
							<th>Location</th>
							<th>Detail Address</th>
							<th>Office Manager</th>
							<th>Office Contact</th>
							<th>Office Email</th>
							<th>Status</th>
							<th></th>
							<th></th>
						</thead>
						<tbody>
							@foreach ($centers as $center)
								<tr>
									<!--
									<td>
											<div class="checkbox">
													<label>
															<input type="checkbox" name="center_ids[]" value="{{ $center->id }}">
													</label>
											</div>
									</td>
									-->
									<td>{{ $center->center_id }}</td>
									<td>{{ $center->name }}</td>
									<td>{{ $center->location_heading }}</td>
									<td>{{ $center->address }}</td>
									<td>{{ $center->office_manager }}</td>
									<td>{{ $center->office_contact_no }}</td>
									<td>{{ $center->office_email }}</td>
									<td>{{ ($center->status) ? 'Enabled' : 'Disabled' }}</td>
									<td><a href="{{ route('center.edit', [$center->id]) }}" class="btn btn-info btn-sm">Edit</a></td>
									<td>
										<form class="form-delete" method="POST" action="{{ route('center.destroy', [$center->id]) }}">
											{{ csrf_field() }}
											<input type="hidden" name="_method" value="delete" />
											<input type="hidden" name="id" value="{{ $center->id }}" />
											<input type="submit" class="btn btn-danger btn-xs" role="button" value="Delete"/>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
					@else
						<h5>No Item's yet, Please add a Center.</h5>
					@endif
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Confirmation Modal Box -->
@include('admin.layouts.modal')

@endsection

@section('page-scripts')
	<!-- DataTables -->
	<script src="{{ asset('js/datatable/jquery.dataTables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/datatable/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

	<!-- page script -->
	<script>
	  $(function () {
	    $('#datatable-all').DataTable()
	  })
	</script>

	<script>
	// For Deletion Confirmation Modal
	$('table[data-form="deleteForm"]').on('click', '.form-delete', function(e){
	    e.preventDefault();
	    var $form=$(this);
	    $('#confirm').modal({ backdrop: 'static', keyboard: false })
	        .on('click', '#delete-btn', function(){
	            $form.submit();
	        });
	});
	</script>
@endsection