routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
* For homepage - Login Page
*/
Route::get('/', 'Auth\LoginController@showLoginForm')->name('welcome');


/*
* For login
*/
//Auth::routes();

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
//Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//Route::post('password/reset', 'Auth\ResetPasswordController@reset');

/*
* For admin-end - Every admin view routes goes here
*/
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function(){
  Route::get('/', 'Admin\HomeController@index')->name('admin.dashboard');
  Route::post('/profile/changepass', 'Admin\ProfileController@edit')->name('profile.changepass');
  Route::resource('center', 'Admin\CenterController', ['except' => 'show']);

  Route::resource('course', 'Admin\CourseController', ['except' => 'show']);

  Route::resource('admin', 'Admin\AdminController', ['except' => 'show']);

  Route::resource('enrollment', 'Admin\EnrollmentController', ['except' => ['create', 'store']]);

  Route::resource('profile', 'Admin\ProfileController', ['except' => 'show']);
  // Tor routes goes here

});

/*
* For user-end - JSON results
*/
Route::group(['prefix' => 'api'], function(){
  Route::get('centers', 'Api\GetController@centers')->name('centers.get');
  Route::get('centers/{id}', 'Api\GetController@center')->name('centers.single');
  //Route::get('courses', 'Api\GetController@courses')->name('courses.get');
  Route::get('courses/{id}', 'Api\GetController@course');
  //Route::post('courses', 'Api\PostController@courses')->name('courses.post');
  //Route::get('admins', 'Api\GetController@admins')->name('admins.get');
  //Route::post('admins', 'Api\PostController@admins')->name('admins.post');
  //Route::get('profiles', 'Api\GetController@profiles')->name('profiles.get');
  //Route::post('profiles', 'Api\PostController@profiles')->name('profiles.post');
  //Route::get('enrollments', 'Api\GetController@enrollments')->name('enrollments.get');
  Route::post('enrollments/create', 'Api\PostController@enrollments')->name('enrollments.post');
});

Route::get('/test/frontend', function(){
  return view('testing.index');
});

Route::get('/test', function(){
  return view('test');
});
Route::get('/registration', 'UserController@index')->name('user.index');

Route::post('/user', 'UserController@getCourse')->name('user.courses');
Route::get('/test/show', 'Admin\CourseController@index');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UserController extends Controller
{
    //
    public function index(){
      return view('user.index');
    }

    public function getCourse(Request $request){
      /*$courses=DB::table('courses')
                    ->where('center_id',$request->id);
                    ->get();*/
      return response();
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.main')

@section('title', 'Create Admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Create Admin</h4>
                        <p class="category">Create new Admin</p>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('admin.store') }}">
                            {{ csrf_field() }}
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Name</label>
                                        <input type="text" class="form-control" name="name">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Email</label>
                                        <input type="email" class="form-control" name="email">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Password</label>
                                        <input type="password" class="form-control" name="password">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Confirm Password</label>
                                        <input type="password" class="form-control" name="confirm_password">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Create</button>
                            <a href="{{ route('admin.index') }}" class="btn btn-primary pull-right">Back</a>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.main')

@section('title', 'Edit Admin')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header" data-background-color="orange">
                        <h4 class="title">Set Password</h4>
                    </div>
                    <div class="card-content">
                        <form method="POST" action="{{ route('admin.update', [$admin->id]) }}">
                            {{ csrf_field() }}
                            <input type="hidden" name="_method" value="put" />
                            <input type="hidden" name="id" value="{{ $admin->id }}" />

                              <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Name</label>
                                        <label class="form-control">{{$admin->name}}</label>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Email</label>
                                        <label class="form-control">{{$admin->email}}</label>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Password</label>
                                        <input type="password" class="form-control" name="password">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group label-floating">
                                        <label class="control-label">Confirm Password</label>
                                        <input type="password" class="form-control" name="confirm_password">
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">Confirm</button>
                            <a href="{{ route('admin.index') }}" class="btn btn-primary pull-right">Back</a>

                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.main')

@section('title', 'Admins')

@section('page-styles')
	<!-- DataTables -->
	<link href="{{ asset('css/datatable/dataTables.bootstrap.min.css') }}" rel="stylesheet" />
@endsection

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<a href="{{ route('admin.create') }}" type="button" class="btn btn-default">Create New Admin</a>
			<div class="card">
				<div class="card-header" data-background-color="orange">
					<h4 class="title">Admin</h4>
					<p class="category">All Admin List</p>
				</div>
				<div class="card-content table-responsive">
				@if ($admins)
				<table id="datatable-all" class="table" data-form="deleteForm">
					<thead class="text-primary">
							<th>Id</th>
							<th>Name</th>
							<th>Email</th>
							<th></th>
							<th></th>
						</thead>
						<tbody>
							@foreach ($admins as $admin)
								<tr>
									<td>{{ $admin->id }}</td>
									<td>{{ $admin->name }}</td>
									<td>{{ $admin->email}}</td>
									<td><a href="{{ route('admin.edit', [$admin->id]) }}" class="btn btn-info btn-sm">Set Password</a></td>
									<td>
										<form class="form-delete" method="POST" action="{{ route('admin.destroy', [$admin->id]) }}">
											{{ csrf_field() }}
											<input type="hidden" name="_method" value="delete" />
											<input type="hidden" name="id" value="{{ $admin->id }}" />
											<input type="submit" class="btn btn-danger btn-xs" role="button" value="Delete"/>
										</form>
									</td>
								</tr>
							@endforeach
						</tbody>
					</table>
					@endif
				</div>
			</div>
		</div>
	</div>
</div>

@include('admin.layouts.modal')

@endsection

@section('page-scripts')
	<!-- DataTables -->
	<script src="{{ asset('js/datatable/jquery.dataTables.min.js') }}" type="text/javascript"></script>
	<script src="{{ asset('js/datatable/dataTables.bootstrap.min.js') }}" type="text/javascript"></script>

	<!-- page script -->
	<script>
	  $(function () {
	    $('#datatable-all').DataTable()
	  })
	</script>

	<script>
	// For Deletion Confirmation Modal
	$('table[data-form="deleteForm"]').on('click', '.form-delete', function(e){
	    e.preventDefault();
	    var $form=$(this);
	    $('#confirm').modal({ backdrop: 'static', keyboard: false })
	        .on('click', '#delete-btn', function(){
	            $form.submit();
	        });
	});
	</script>
@endsection